
import {
  Droplet,
  Clock,
  CalendarClock,
  Syringe,
  TestTube,
  TestTubes,
  FlaskConical,
  FlaskRound,
  Package,
  Package2,
  Truck,
  FileText,
  CalendarCheck,
  BookCopy,
  Calculator,
  ClipboardCheck,
  Star,
  TrendingUp,
  Stethoscope,
} from "lucide-react";

export const Icons = {
  droplet: Droplet,
  clock: Clock,
  "clock-3": Clock,
  "calendar-clock": CalendarClock,
  syringe: Syringe,
  "test-tube": TestTube,
  "test-tubes": TestTubes,
  flask: FlaskConical,
  "flask-round": FlaskRound,
  package: Package,
  "package-2": Package2,
  truck: Truck,
  "file-text": FileText,
  calendar: CalendarCheck,
  book: BookCopy,
  calculator: Calculator,
  clipboard: ClipboardCheck,
  star: Star,
  trending: TrendingUp,
  stethoscope: Stethoscope,
};
